#!/usr/bin/env python

import os
import subprocess
import sys

import pyEdit

if __name__ == '__main__':
    path = os.path.join(os.path.dirname(pyEdit.__file__), 'MainWindow.py')
    subprocess.call([sys.executable, path] + sys.argv[1:])
